---
- name: "Remove RSA pub key from target hosts | {{ item }}"
  authorized_key:
    user: "{{ ssh_setup_user }}"
    path: "{{ ssh_setup_ssh_auth_key_path }}"
    state: absent
    manage_dir: False
    comment: "{{ ssh_setup_source_host }}"
    key: "{{ ssh_setup_pub_key_content.content | b64decode | string }}"
  no_log: True
  delegate_to: "{{ item }}"
  when: ssh_setup_pub_key_content.content is defined

- name: Remove {{ ssh_setup_user }} from /etc/security/access-ssh.conf | {{ item }}
  lineinfile:
    path: "/etc/security/access-ssh.conf"
    line: "{{ ssh_setup_user }}"
    state: absent
  become: yes
  delegate_to: "{{ item }}"

- name: Remove {{ ssh_setup_user }} from /etc/restricted_accounts | {{ item }}
  lineinfile:
    path: "/etc/restricted_accounts"
    line: "{{ ssh_setup_user }}"
    state: absent
  become: yes
  delegate_to: "{{ item }}"

- name: "Remove {{ item }} from known_host of {{ ssh_setup_source_host }}"
  known_hosts:
    name: "{{ item }}"
    state: absent
  become: yes
  become_method: "{{ ssh_setup_default_become_method }}"
  become_user: "{{ ssh_setup_user }}"
  delegate_to: "{{ ssh_setup_source_host }}"