---
# tasks file for grafana


- name: Install haproxy
  yum:
    name:
        - haproxy

- name: "Copy haproxy conf"
  template:
    src: haproxy.conf.j2
    dest: "/etc/haproxy/haproxy.cfg"
  notify: restart haproxy