---

- name: Register primary node
  become_user: postgres
  shell: repmgr primary register
  ignore_errors: yes
  when: role == "primary"

- name: stop postgres
  service:
    name: "{{ postgresql_service_name }}"
    state: stopped
  when: role == "standby"